### ISSUE TITLE
Crash when open coordinate folder

### ISSUE THREAD

**Issue by thorstenwagner** [MPI-Dortmund/napari-boxmanager#25]
This happens when you try to open a folder via command line or via GUI:

```python
Traceback (most recent call last):
  File "/home/twagner/.conda/envs/napari-cryolo-test/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/__main__.py", line 341, in _run
    viewer._window._qt_viewer._qt_open(
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 830, in _qt_open
    self.viewer.open(
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/plugins/io.py", line 77, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "/home/twagner/.local/lib/python3.10/site-packages/napari/plugins/_npe2.py", line 55, in read
    layer_data, reader = io_utils.read_get_reader(
  File "/home/twagner/.local/lib/python3.10/site-packages/npe2/io_utils.py", line 66, in read_get_reader
    return _read(
  File "/home/twagner/.local/lib/python3.10/site-packages/npe2/io_utils.py", line 165, in _read
    if layer_data := read_func(paths, stack=stack):
  File "/home/twagner/.local/lib/python3.10/site-packages/npe2/manifest/contributions/_readers.py", line 60, in npe1_compat
    return callable_(path)  # type: ignore
  File "/mnt/data/twagner/Projects/napari/src/napari-boxmanager-github/src/box_manager/_reader.py", line 47, in get_dir
    is_first_file_tomo=is_tomo(files[0],reader)
UnboundLocalError: local variable 'reader' referenced before assignment

```

**Comment by thorstenwagner** [comment]
Fixed https://github.com/MPI-Dortmund/napari-boxmanager/pull/30
